// Unique intro per goal × equipment combination (4 × 5 = 20 intros).
// Each combined with one of 3 experience suffixes → 60 unique 2-paragraph blocks
// across all SEO landing pages. Keeps pages distinct enough to avoid being
// flagged as duplicate / thin content by search engines.

export const GOAL_EQUIPMENT_INTRO = {
  'build-muscle': {
    'full-gym': 'Building muscle in a commercial gym gives you everything you need: barbells for heavy compounds, dumbbells for variation, machines for safer isolation work, and cables for constant tension. The plan uses all four — squat / bench / deadlift / row / overhead press as the foundation, dumbbells and machines for accessories, and cables for shoulders, arms and core. The training split adapts to your weekly frequency, from full-body for low days to upper/lower or push/pull/legs for higher.',
    'home-dumbbells': 'A pair of adjustable dumbbells and a bench is enough to build real muscle for years. The plan replaces barbell compounds with dumbbell equivalents — dumbbell bench, goblet squats, Bulgarian split squats, single-leg Romanian deadlifts — and stacks the volume to compensate for the lower absolute load. With a 5–50 kg adjustable range, progressive overload is virtually unlimited for most lifters.',
    'home-barbell': 'A home barbell setup with rack, plates and bench is the gold standard for size and strength. The plan revolves around the big compounds — squat, bench, deadlift, overhead press, barbell row — with dumbbell accessories for arms, side delts and rear delts. Owning the bar means no commute, no waiting on equipment, and clean 1.25–2.5 kg progression for as long as you keep training.',
    'bodyweight': 'Building muscle with only bodyweight is harder than with weights, but it works — especially for the upper body and core. The plan progresses through harder exercise variations rather than adding load: kneeling push-ups → push-ups → archer push-ups → one-arm work, assisted pull-ups → strict pull-ups → weighted pull-ups (using a backpack). Lower body relies on single-leg work, tempo squats and plyometrics to keep stimulus high.',
    'bands': 'Resistance bands aren’t a complete strength tool, but they let you build noticeable muscle if you commit to high volume and strict tempo. The plan uses bands for every major movement pattern — squats, hinges, rows, presses — with extra sets to compensate for sub-maximal load. Bonus: bands provide constant tension through the full range of motion, a stimulus barbells genuinely cannot replicate.'
  },
  'lose-fat': {
    'full-gym': 'Fat loss happens in the kitchen, but a smart resistance plan preserves the muscle you’ve already built (so you lose fat, not weight) and burns enough calories to matter. At a full gym, the plan stacks compound lifts for big metabolic cost and adds short circuits or supersets at the end of sessions. Cardio equipment is optional — the resistance work alone is enough if your eating is in check.',
    'home-dumbbells': 'Losing fat with home dumbbells is fully viable and arguably more time-efficient than a gym membership. The plan combines dumbbell compounds (presses, rows, goblet squats, lunges) with dense supersets and short rest to maximise calorie burn per session. No cardio equipment needed — bodyweight conditioning (burpees, mountain climbers, jumping lunges) plugs straight in.',
    'home-barbell': 'A home barbell setup is excellent for fat loss because you can train heavy 4–5x per week without commute time eating into your day. The plan keeps the heavy compounds (squat, deadlift, press) for muscle retention and adds dumbbell-based metabolic finishers plus optional outdoor cardio. With food on point, expect 0.5–1% bodyweight loss per week without losing strength.',
    'bodyweight': 'Fat loss with only bodyweight is mostly about consistency and food. The plan uses high-volume circuits — squats, push-ups, lunges, planks — designed to be done anywhere in 30–45 minutes. Conditioning (burpees, mountain climbers, jumping jacks) provides the calorie burn, and the zero-equipment requirement removes every excuse for skipping a session.',
    'bands': 'Bands for fat loss work surprisingly well in circuit format. The plan strings together band squats, rows, presses and rotations into 30–45 minute high-density sessions you can do in a hotel room with a single piece of equipment. The constraint forces you to focus on tempo, position and contraction quality instead of chasing weight on the bar.'
  },
  'general-fitness': {
    'full-gym': 'General fitness means moving well, being strong enough for daily life, and not getting winded climbing stairs. A full gym gives you the best of all worlds: barbell strength, machine isolation for joint health, dumbbells for variation, and cardio equipment for conditioning. The plan blends all four into 3–4 balanced sessions per week, each finishing with a short cardio or conditioning piece.',
    'home-dumbbells': 'Home dumbbells are arguably the perfect general-fitness tool. The plan covers all movement patterns — push, pull, squat, hinge, lunge, carry — in 3–4 sessions per week, each around 45 minutes including warm-up. If you commit to the conditioning circuits, no separate cardio equipment is necessary; the same dumbbells handle strength and conditioning.',
    'home-barbell': 'A home barbell makes general fitness training simple and time-efficient. The plan revolves around the five big lifts — squat, bench, deadlift, press, row — done 3–4 times per week with brief accessory work and a short conditioning piece. Sessions are 30–45 minutes door-to-door, with no commute, and you get stronger, leaner and more capable each month.',
    'bodyweight': 'General fitness with only bodyweight is the most accessible path into training. No equipment, no gym, no excuses. The plan rotates between strength-focused sessions (push-up and pull-up variants, squats, lunges) and conditioning days (intervals, sprints if available, brief mobility work). Two months in, most people are noticeably stronger and visibly fitter.',
    'bands': 'A set of resistance bands gives you the equivalent of a portable gym. The plan trains all major movement patterns — squats, rows, presses, hinges, rotations — with bands as the primary resistance, plus bodyweight conditioning for cardiovascular health. Everything fits in a backpack, which makes consistency easier on travel and busy weeks.'
  },
  'endurance': {
    'full-gym': 'Endurance training in a full gym lets you blend cardiovascular work (treadmill, bike, rower) with strength endurance (higher-rep lifting). The plan structures sessions around heart-rate zones — Z2 base building, Z3–4 tempo, occasional Z5 intervals — and keeps lower-rep strength work in the mix to maintain power output and protect joints across high weekly volume.',
    'home-dumbbells': 'Endurance with dumbbells means high-rep circuits and movement complexes. The plan strings together dumbbell movements — thrusters, clean and press, lunges, renegade rows — into work-rest intervals that build aerobic capacity and muscular endurance simultaneously. Pair with outdoor running or cycling 1–2x per week for the cardiovascular base.',
    'home-barbell': 'Endurance with a barbell uses complexes (multi-exercise unbroken sets) and EMOM formats (every minute on the minute) to build conditioning while maintaining a strength base. The plan blends light barbell work with bodyweight movements and assumes you’ll add some form of pure cardio — running, cycling, rowing — separately, 2–3 times per week.',
    'bodyweight': 'Bodyweight is the natural pairing with endurance training — burpees, mountain climbers, jumping lunges, squat thrusts, with running as the obvious complement. The plan structures progressive cardio plus strength-endurance circuits across the week. No equipment is needed, which makes it ideal for travel, irregular schedules and limited spaces.',
    'bands': 'Bands for endurance work in circuit and high-rep formats. The plan combines band-resisted movement patterns with bodyweight conditioning and whatever outdoor cardio you can access. Everything is light and portable — no gym membership, no power required — which suits the endurance athlete’s tendency to train wherever the road or trail leads.'
  }
};

export const EXPERIENCE_SUFFIX = {
  'beginner': 'As a beginner (under one year of consistent training), prioritise form over load every single session. Week 1 is calibration — pick weights you can finish with 2–3 reps left in the tank. Only add load once you can complete the top of the rep range with clean technique. Progress will feel slow for the first month and then accelerate sharply.',
  'intermediate': 'At intermediate level (1–3 years of consistent training), weekly progression is the engine of the program. Track your top sets and aim to add 2.5 kg or 1 rep every week through the first three weeks; week four deloads to consolidate gains and let connective tissue recover. Plateaus usually mean recovery is the limiter, not effort.',
  'advanced': 'As an advanced lifter (3+ years of consistent training), expect smaller weekly gains and use the deload week aggressively. Intensity techniques on accessory work — drop sets, rest-pause, slow eccentrics — let you keep progressing when straight-set linear progression stalls on the main lifts. Sleep, food and stress management matter more now than program design.'
};
